---
nesi_extra_repos:
  - name: epel
    file: epel
    description: "Extra Packages for Enterprise Linux $releasever - $basearch"
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir"
    gpgcheck: true
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"

system_packages:
  - python3-pip
  - munge

compute_packages:
  - dnf-plugins-core
  - glibc-langpack-en
  - yum-utils
  - epel-release
  - man
  - man-pages
  # System things, these are just guesses, no doubt there are many more needed
  - logrotate
  - net-tools
  - nvme-cli
  - sssd
  - tcpdump
  - golang-github-prometheus-node-exporter
  # Infiniband
  - librdmacm
  - ibacm
  # Tools
    # parsing
  - bison
  - byacc
  - flex
    # misc
  - gnuplot
  - intltool
  - dos2unix
  - GraphicsMagick
  - jq
  - texlive
  - lighttpd  # for Trinotate
    # dev
  - gdb
  - ctags
  - patchutils
  - diffutils
    # building
  - libtool
  - m4
  - autoconf
  - automake
  - make
  - patch
  - swig
    # network
  - wget
  - rsync
  - telnet
  - s-nail
  - lynx
    # compression
  - bzip2
  - zip
  - unzip
  - bsdtar
  - p7zip
    # system
  - which
  - time
  - sudo
  - strace
  - ltrace
  - lsof
  - quota
  - file
  - patchelf
  - psmisc
   # HPC
  - Lmod
  - datamash
  - stress
  - pigz
    # interpreters
  - python-unversioned-command
  - perl
  - ruby
  - bc
    # version control
  - subversion
  - git
  - git-lfs
    # editors
  - vim-enhanced
  - emacs
  - emacs-nox
  - nano
  - gedit
  - ed
    # Shells
  - fish
  - zsh
  - ksh
  - tcsh
  - bash-completion
    # Terminal things
  - tmux
  - screen
  - mc
  - tree
  - htop
  - pspg
  - expect
    # pdsh
  - pdsh
  - pdsh-rcmd-ssh
    # x11
  - xterm
  - xorg-x11-server-Xvfb
    # NeSI tools
  - postgresql
  - python3-psycopg2
  - python3-sqlalchemy
  - python3-dateutil
  - python3-click
    # perl extensions
  - perl-Clone
  - perl-Digest-SHA
  - perl-Tk
  - perl-Config-IniFiles
  - perl-ExtUtils-PkgConfig
  - perl-Text-Format
  - perl-XML-LibXML
   # Libraries which user programs can reasonably build against
    # basics
  - glibc-devel
  - glib2-devel
  - libffi-devel
    # network
  - curl
  - openssl-devel
  - libssh2-devel
  - libcurl-devel
    # XALT
  - elfutils-libelf-devel
    # terminal
  - readline-devel
  - ncurses-devel
    # images
  - jbigkit-devel
  - libjpeg-turbo-devel
  - libpng-devel
  - libtiff-devel
  - giflib-devel
  - libwebp-devel
    # drawing
  - gd-devel
  - cairo-devel
    # fonts
  - pango-devel
  - fontconfig-devel
  - libfontenc-devel
  - freetype-devel
  - graphite2-devel
  - harfbuzz-devel
    # text
  - expat-devel
  - gettext-devel
  - libunistring-devel
  - libxml2-devel
  - libxslt-devel
  - pcre-devel
  - pcre2-devel
  - json-c-devel
    # X11
  - libdrm-devel
  - libICE-devel
  - libX11-devel
  - libXdmcp-devel
  - libXext-devel
  - libXfont2-devel
  - libXrandr-devel
  - libXrender-devel
  - libXaw-devel
  - libXft-devel
  - libXmu-devel
  - libXpm-devel
  - libXScrnSaver-devel
  - libXt-devel
  - libXtst-devel
  - libXv-devel
  - libxkbfile-devel
    # GUIs
  - libxshmfence-devel
  - libxcb-devel
  - freeglut-devel
  - motif-devel
  - gtk2-devel
  - gtk3-devel
  - qt5-qtbase-devel
  - tcl-devel
  - tk-devel
    # compression
  - bzip2-devel
  - libzstd-devel
  - lz4-devel
  - lzo-devel
  - snappy-devel
  - xz-devel
  - zlib-devel
  - libarchive-devel
  - libaec-devel
    # hardware
  - libpciaccess-devel
  - hwloc-devel
  - numactl-devel
  - lm_sensors-devel
    # databases
  - libdb-devel
  - gdbm-devel
  - mariadb-connector-c-devel
  - libpq-devel
  - sqlite-devel
  - lmdb-devel
  - apr-devel
  - apr-util-devel
  - apr-util-sqlite
    # misc
  - zeromq-devel
  - libquadmath-devel
  - java-21-openjdk-devel
  # Slurm
  - lua-devel
  - libjwt-devel
  - munge-devel
  - http-parser-devel
  - freeipmi-devel
  - pam-devel
  # Back compatibility
  - compat-openssl11
  - libffi3.1
  - libicu50
  - ncurses-compat-libs
  - libpng12
  - libpng15
  - libnsl
  # Apptainer requirements
  - e2fsprogs
  - fakeroot
  - fuse-overlayfs
  #- fuse2fs
  - libseccomp
  - squashfs-tools
  - squashfuse
  - cryptsetup
